language: php
php:
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
